---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: windows-2022
    driver:
      box: gusztavvargadr/windows-server-2022-standard
      communicator: winrm
      memory: 4096
      cpus: 2

suites:
  - name: default
    run_list:
      - recipe[stew::default]
    attributes:
      # Override attributes here if needed 